default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 3306
  username: root
  password: 151819lz.
#  socket: /tmp/mysql.sock

development:
  <<: *default
  database: contract
